location: .gitman
sources:
  - repo: git@github.com:LASER-Robotics/laser_fast_lio_core.git
    name: laser_fast_lio_core
    rev: release/1.0
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/laser_fast_lio
    scripts:
      - git submodule update --init --recursive
