location: .gitman
sources:
  - repo: git@github.com:LASER-Robotics/livox_ros_driver2.git
    name: livox_ros_driver2
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/livox_ros_drivers
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:LASER-Robotics/FAST_LIO.git
    name: FAST_LIO
    rev: main
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/fast_lio
    scripts:
      - git submodule update --init --recursive
