location: .gitman
sources:
  - repo: git@github.com:LASER-Robotics/FAST_LIO.git
    name: FAST_LIO
    rev: main
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/fast_lio
    scripts:
      - git submodule update --init --recursive
